apiVersion: v1
kind: ConfigMap
metadata:
  name: my-django-config
data:
  DEBUG: "True"
  ALLOWED_HOSTS: "*"
---
apiVersion: v1
kind: Secret
metadata:
  name: my-django-secret
type: Opaque
data:
  SECRET_KEY: ""
  DATABASE_URL: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-django-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-python-app
  template:
    metadata:
      labels:
        app: simple-python-app
    spec:
      containers:
      - name: simple-python-app-container
        image: kaustubhraut/simple-python-app
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: my-django-config
        - secretRef:
            name: my-django-secret
---
apiVersion: v1
kind: Service
metadata:
  name: my-django-service
spec:
  selector:
    app: simple-python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
